#!/usr/bin/env bash
# Install local git hooks for this repo. Idempotent.
#
# Writes a pre-push hook that runs scripts/pre-pr-check.sh before allowing the
# push to proceed. Bypass with `git push --no-verify` (or `jj git push
# --no-verify`) when you genuinely need to.
#
# Run from the repo root: ./scripts/install-hooks.sh

set -eu

# --- locate the .git dir ---------------------------------------------------
#
# `git rev-parse --git-common-dir` resolves the right place for both:
# - Regular checkouts (./.git)
# - Worktrees and jj workspaces (../<main>/.git)
# Hooks installed there fire for any worktree, which is what we want.

if ! GIT_COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null)"; then
  echo "install-hooks: git rev-parse failed — are you inside the mu repo?" >&2
  exit 1
fi

# Normalize to absolute path
case "$GIT_COMMON_DIR" in
  /*) ;;
  *) GIT_COMMON_DIR="$(pwd)/$GIT_COMMON_DIR" ;;
esac

HOOKS_DIR="$GIT_COMMON_DIR/hooks"
TARGET="$HOOKS_DIR/pre-push"

mkdir -p "$HOOKS_DIR"

# Back up any existing non-trivial hook
if [ -f "$TARGET" ] && ! grep -q "pre-pr-check.sh" "$TARGET" 2>/dev/null; then
  backup="$TARGET.bak.$(date +%Y%m%d%H%M%S)"
  echo "install-hooks: backing up existing pre-push hook to $backup"
  mv "$TARGET" "$backup"
fi

cat > "$TARGET" <<'HOOK'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — do not edit by hand.
# Re-run scripts/install-hooks.sh to regenerate.
#
# Runs scripts/pre-pr-check.sh before allowing push. Bypass with --no-verify.

set -e

# Locate the repo root. jj workspaces don't have .git at their root, so try jj first.
if command -v jj >/dev/null 2>&1 && jj root >/dev/null 2>&1; then
  ROOT="$(jj root)"
else
  ROOT="$(git rev-parse --show-toplevel)"
fi

CHECK="$ROOT/scripts/pre-pr-check.sh"

if [ ! -x "$CHECK" ]; then
  echo "pre-push hook: $CHECK not found or not executable; skipping" >&2
  exit 0
fi

exec "$CHECK"
HOOK

chmod +x "$TARGET"

echo "install-hooks: installed $TARGET"
echo "install-hooks: bypass with 'git push --no-verify' or 'jj git push --no-verify' if needed"
